name: ipso_phen
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pyside2
  - imageio
  - jupyterlab
  - markdown
  - paramiko
  - psutil
  - psycopg2-binary
  - seaborn
  - sqlalchemy
  - sqlalchemy-utils
  - tqdm
  - unidecode
  - opencv
  - scikit-image
  - scikit-learn
  - scipy
  - black
  - pip
  - pip:
    - streamlit
