# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\fmavianemac\Documents\Felicia\ipso_phen\ui\frm_new_tool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlg_new_tool(object):
    def setupUi(self, dlg_new_tool):
        dlg_new_tool.setObjectName("dlg_new_tool")
        dlg_new_tool.resize(570, 463)
        dlg_new_tool.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(dlg_new_tool)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.te_description = QtWidgets.QTextEdit(dlg_new_tool)
        self.te_description.setObjectName("te_description")
        self.gridLayout.addWidget(self.te_description, 3, 0, 1, 6)
        self.label = QtWidgets.QLabel(dlg_new_tool)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lbl_file_exists = QtWidgets.QLabel(dlg_new_tool)
        self.lbl_file_exists.setText("")
        self.lbl_file_exists.setPixmap(QtGui.QPixmap("../resources/OK.png"))
        self.lbl_file_exists.setObjectName("lbl_file_exists")
        self.gridLayout.addWidget(self.lbl_file_exists, 0, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(dlg_new_tool)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.chk_mask_required = QtWidgets.QCheckBox(dlg_new_tool)
        self.chk_mask_required.setObjectName("chk_mask_required")
        self.gridLayout.addWidget(self.chk_mask_required, 5, 0, 1, 6)
        self.label_4 = QtWidgets.QLabel(dlg_new_tool)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.le_tool_name = QtWidgets.QLineEdit(dlg_new_tool)
        self.le_tool_name.setObjectName("le_tool_name")
        self.gridLayout.addWidget(self.le_tool_name, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(dlg_new_tool)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 3, 1, 1)
        self.le_file_name = QtWidgets.QLineEdit(dlg_new_tool)
        self.le_file_name.setReadOnly(True)
        self.le_file_name.setObjectName("le_file_name")
        self.gridLayout.addWidget(self.le_file_name, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(dlg_new_tool)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.le_class_name = QtWidgets.QLineEdit(dlg_new_tool)
        self.le_class_name.setReadOnly(True)
        self.le_class_name.setObjectName("le_class_name")
        self.gridLayout.addWidget(self.le_class_name, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(dlg_new_tool)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 6)
        self.label_7 = QtWidgets.QLabel(dlg_new_tool)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.le_package_name = QtWidgets.QLineEdit(dlg_new_tool)
        self.le_package_name.setObjectName("le_package_name")
        self.gridLayout.addWidget(self.le_package_name, 4, 1, 1, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(dlg_new_tool)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_output_image = QtWidgets.QRadioButton(self.groupBox)
        self.rb_output_image.setChecked(True)
        self.rb_output_image.setObjectName("rb_output_image")
        self.verticalLayout.addWidget(self.rb_output_image)
        self.rb_output_mask = QtWidgets.QRadioButton(self.groupBox)
        self.rb_output_mask.setObjectName("rb_output_mask")
        self.verticalLayout.addWidget(self.rb_output_mask)
        self.rb_output_data = QtWidgets.QRadioButton(self.groupBox)
        self.rb_output_data.setObjectName("rb_output_data")
        self.verticalLayout.addWidget(self.rb_output_data)
        self.rb_output_none = QtWidgets.QRadioButton(self.groupBox)
        self.rb_output_none.setObjectName("rb_output_none")
        self.verticalLayout.addWidget(self.rb_output_none)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.gb_pipeline_tool_groups = QtWidgets.QGroupBox(dlg_new_tool)
        self.gb_pipeline_tool_groups.setObjectName("gb_pipeline_tool_groups")
        self.verticalLayout_4.addWidget(self.gb_pipeline_tool_groups)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(dlg_new_tool)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_rt_yes = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_rt_yes.setObjectName("rb_rt_yes")
        self.verticalLayout_2.addWidget(self.rb_rt_yes)
        self.rb_rt_no = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_rt_no.setChecked(True)
        self.rb_rt_no.setObjectName("rb_rt_no")
        self.verticalLayout_2.addWidget(self.rb_rt_no)
        self.rb_rt_widget = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_rt_widget.setObjectName("rb_rt_widget")
        self.verticalLayout_2.addWidget(self.rb_rt_widget)
        self.rb_rt_property = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_rt_property.setObjectName("rb_rt_property")
        self.verticalLayout_2.addWidget(self.rb_rt_property)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.gb_no_pipeline_tool_groups = QtWidgets.QGroupBox(dlg_new_tool)
        self.gb_no_pipeline_tool_groups.setObjectName("gb_no_pipeline_tool_groups")
        self.verticalLayout_3.addWidget(self.gb_no_pipeline_tool_groups)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.bt_save = QtWidgets.QPushButton(dlg_new_tool)
        self.bt_save.setObjectName("bt_save")
        self.horizontalLayout.addWidget(self.bt_save)
        self.bt_cancel = QtWidgets.QPushButton(dlg_new_tool)
        self.bt_cancel.setObjectName("bt_cancel")
        self.horizontalLayout.addWidget(self.bt_cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)

        self.retranslateUi(dlg_new_tool)
        QtCore.QMetaObject.connectSlotsByName(dlg_new_tool)

    def retranslateUi(self, dlg_new_tool):
        _translate = QtCore.QCoreApplication.translate
        dlg_new_tool.setWindowTitle(_translate("dlg_new_tool", "New tool wizard"))
        self.te_description.setPlaceholderText(_translate("dlg_new_tool", "Write your tool\'s description here.\\nYou can use HTML tags"))
        self.label.setText(_translate("dlg_new_tool", "Tool name:"))
        self.label_5.setText(_translate("dlg_new_tool", "File name:"))
        self.chk_mask_required.setText(_translate("dlg_new_tool", "Requires mask in input"))
        self.label_4.setText(_translate("dlg_new_tool", "🡢"))
        self.label_3.setText(_translate("dlg_new_tool", "Class name"))
        self.label_6.setText(_translate("dlg_new_tool", "🡢"))
        self.label_2.setText(_translate("dlg_new_tool", "Description:"))
        self.label_7.setText(_translate("dlg_new_tool", "Package:"))
        self.groupBox.setTitle(_translate("dlg_new_tool", "Output:"))
        self.rb_output_image.setText(_translate("dlg_new_tool", "Image"))
        self.rb_output_mask.setText(_translate("dlg_new_tool", "Mask"))
        self.rb_output_data.setText(_translate("dlg_new_tool", "Data"))
        self.rb_output_none.setText(_translate("dlg_new_tool", "None"))
        self.gb_pipeline_tool_groups.setTitle(_translate("dlg_new_tool", "Groups that can be added to pipelines"))
        self.groupBox_2.setTitle(_translate("dlg_new_tool", "Real time:"))
        self.rb_rt_yes.setText(_translate("dlg_new_tool", "Yes"))
        self.rb_rt_no.setText(_translate("dlg_new_tool", "No"))
        self.rb_rt_widget.setText(_translate("dlg_new_tool", "Widget"))
        self.rb_rt_property.setText(_translate("dlg_new_tool", "Property"))
        self.gb_no_pipeline_tool_groups.setTitle(_translate("dlg_new_tool", "Groups forbiden in pipelines"))
        self.bt_save.setText(_translate("dlg_new_tool", "Save"))
        self.bt_cancel.setText(_translate("dlg_new_tool", "Close"))

